config/routes.rb
Rails.application.routes.draw do


  root to: "home#index"

  resources :klasses do
    member do
      get :teachers
      get :add_teacher
      post :save_teacher
    end
  end

  resources :subjects
  resources :teachers do
    member do
      get :subjects
      get :add_subjects
      post :save_subject
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klass.rb
class Klass < ApplicationRecord
  has_many :klass_subjects
  has_many :subjects, through: :klass_subjects

  has_many :teacher_klasses
  has_many :teachers, through: :teacher_klasses
end

app/models/klass_subject.rb
class KlassSubject < ApplicationRecord
  belongs_to :klass
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :subject_teachers
  has_many :teachers, through: :subject_teachers

  has_many :klass_subjects
  has_many :klasses, through: :klass_subjects

  validates :name, presence: true
  validates :title, presence: true
  #validates :teachers, presence: true
#  validates :klasses, presence: true
end

app/models/subject_teacher.rb
class SubjectTeacher < ApplicationRecord
  belongs_to :subject
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :subject_teachers
  has_many :subjects, through: :subject_teachers

  has_many :teacher_klasses
  has_many :klasses, through: :teacher_klasses

  validates :name, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :email, presence: true
end

app/models/teacher_klass.rb
class TeacherKlass < ApplicationRecord
  belongs_to :teacher
  belongs_to :klass
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  before_action :set_klass, only: [:show, :edit, :update, :destroy, :add_teacher, :save_teacher]
  def new
    @klass = Klass.new
  end

  def create
    @klass = Klass.new(klass_params)
    respond_to do |format|
      if@klass.save
        format.html{redirect_to @klass, notice: "klass was successfully created"}
      else
        format.html{redirect_to :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @klass.update(klass_params)
        format.html { redirect_to @klass, notice: 'Klass was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def edit

  end

  def destroy
    @klass.destroy
    respond_to do |format|
      format.html { redirect_to klasses_url , notice: "klass delete succesfully"}
     end
  end

  def index
    @klass = Klass.all
  end

  def show
  end

  def teachers
    @klass = Klass.find(params[:id])
  end

  def add_teacher
     @teacher = Teacher.where.not(id:@klass.teachers.ids)
  end
  def save_teacher

    teacher = Teacher.find(params[:teacher_id])
    p teacher
    @klass.teachers << teacher

    if@klass.save
      flash[:success] = "Add this teacher successfully to the class"
    end
  end



  private
  def set_klass
    @klass = Klass.find(params[:id])
  end
  def klass_params
    params.require(:klass).permit(:name)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    p subject_params
    if @subject.save
      redirect_to @subject, notice: "subject was successfully created"
    else
      render 'new'
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: 'subject was successfully updated.'
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url , notice: "subject delete succesfully"}
    end
  end


  def index
    @subject = Subject.all
  end

  def show

  end

  private
  def set_subject
    @subject = Subject.find(params[:id])
  end
  def subject_params
    params.require(:subject).permit(:name, :title)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy, :add_subjects, :save_subject]

  def index
    @teacher = Teacher.all
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def new
    @teacher = Teacher.new
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: 'teacher was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url , notice: "teacher delete succesfully"}
    end
  end


  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to @teacher, notice: "teacher was successfully created"
    else
      render 'new'
    end
  end

  def subjects
    @teacher = Teacher.find(params[:id])
  end

  def add_subjects
    @subjects = Subject.where.not(id:@teacher.subjects.ids)
  end

  def save_subject
    subject = Subject.find(params[:subject_id])
    @teacher.subjects << subject

    if@teacher.save
      flash[:success] = "Add this subject successfully to the this teacher"
    end
  end



  private

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :address, :phone, :email  )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/klasses/_form.html.erb
<%= form_for @klass do |form| %>
    <% if klass.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(klass.errors.count, "error") %> prohibited this klass from being saved:</h2>

          <ul>
            <% klass.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :klass_name %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/klasses/add_teacher.html.erb
<h2>hi</h2>
<%= form_tag save_teacher_klass_url  do %>
    <%= select_tag :teacher_id, options_for_select( @teacher.all.collect {|d| [ d.name, d.id ] }) %>
    <%= submit_tag "Add" %>
<% end %>

<script type="text/javascript">
    $( "#teacher_id" ).change(function() {
        var item=$(this);

        $.ajax({
            url: "<%= subjects_teacher_path %>",
            type: "get",
            data: {"teacher_id" : $(this).val()},
            dataType: "script",
            success: function(data) {
                alert('successfully');
            }
        });
    });

</script>

app/views/klasses/create.html.erb
<h1>Klasses#create</h1>
<p>Find me in app/views/klasses/create.html.erb</p>

app/views/klasses/destroy.html.erb
<h1>Klasses#destroy</h1>
<p>Find me in app/views/klasses/destroy.html.erb</p>

app/views/klasses/edit.html.erb
<h1>Editing Klass</h1>

<%= render 'form', klass: @klass %>

<%= link_to 'Show', @klass %> |
<%= link_to 'Back', klasses_path %>

app/views/klasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Klasses</h1>

<table>
  <thead>
  <tr>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @klass.each do |klass| %>
      <tr>
        <td><%= klass.name %></td>
        <td><%= link_to 'Show', klass %></td>
        <td><%= link_to 'Edit', edit_klass_path(klass) %></td>
        <td><%= link_to 'Destroy', klass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Klass', new_klass_path %>

app/views/klasses/new.html.erb
<h1>New Klass</h1>

<%= render 'form', klass: @klass %>

<%= link_to 'Back', klasses_path %>

app/views/klasses/save_teacher.html.erb
<p><%= flash[:success] %></p>

app/views/klasses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @klass.name %>
</p>
<%= link_to 'Teachers', teachers_klass_path %></br>
<%= link_to 'Edit', edit_klass_path(@klass) %> |
<%= link_to 'Back', klasses_path %>

app/views/klasses/teachers.erb
<p id="notice"><%= notice %></p>

<h1>Teachers Of this Class</h1>

<table>
  <thead>
  <tr>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @klass.teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "add Teacher",  add_teacher_klass_path %>

app/views/klasses/update.html.erb
<h1>Klasses#update</h1>
<p>Find me in app/views/klasses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="fixed-left widescreen">
<body class="fixed-left">

<div id="wrapper">

<%= render "shared/navBar" %>

  <%= render "shared/left_sidebar" %>

  <div class="content-page">
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
          </div>
        </div>
        <%= yield %>
        </div>
      </div>
    </div>
    <footer class="footer">
      2017 © Flacto. Design by <a href="http://coderthemes.com/" target="_blank" class="text-muted">Coderthemes</a>
    </footer>

  </div>
</div>



</body>
</body>
</html>

app/views/shared/_left_sidebar.html.erb
<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
  <div class="sidebar-inner slimscrollleft">
    <!--- Divider -->
    <div id="sidebar-menu">
      <ul>
        <li class="text-muted menu-title">Navigation</li>
        <li class="has_sub">
          <%= link_to  teachers_path , class:" view-dashboard" do %>
              <i class="zmdi zmdi-invert-colors">Teachers</i>
          <% end %>
        </li>
      </ul>
      <ul>
        <li class="has_sub">
          <%= link_to  klasses_path , class:" view-dashboard" do %>
              <i class="zmdi zmdi-invert-colors">Class</i>
          <% end %>
        </li>
      </ul>
      <ul>
        <li class="has_sub">
          <%= link_to  subjects_path , class:" view-dashboard" do %>
              <i class="zmdi zmdi-invert-colors">Subjects</i>
          <% end %>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>

  </div>
</div>
<!-- Left Sidebar End -->

app/views/shared/_navBar.html.erb
<!-- Top Bar Start -->
<div class="topbar">

  <!-- LOGO -->
  <div class="topbar-left">
    <div class="text-center">
      <a href="index.html" class="logo">
        <i class="zmdi zmdi-toys icon-c-logo"></i><span>Flac<span>to</span></span>
        <!--<span><img src="assets/images/logo.png" alt="logo" style="height: 20px;"></span>-->
      </a>
    </div>
  </div>

  <!-- Button mobile view to collapse sidebar menu -->
  <div class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="">
        <div class="pull-left">
          <button class="button-menu-mobile open-left waves-effect waves-light">
            <i class="zmdi zmdi-menu"></i>
          </button>
          <span class="clearfix"></span>
        </div>

        <form role="search" class="navbar-left app-search pull-left hidden-xs">
          <input type="text" placeholder="Search..." class="form-control">
          <a href="#"><i class="fa fa-search"></i></a>
        </form>


        <ul class="nav navbar-nav navbar-right pull-right">
          <li>
            <!-- Notification -->
            <div class="notification-box">
              <ul class="list-inline m-b-0">
                <li>
                  <a href="javascript:void(0);" class="right-bar-toggle">
                    <i class="zmdi zmdi-notifications-none"></i>
                  </a>
                  <div class="noti-dot">
                    <span class="dot"></span>
                    <span class="pulse"></span>
                  </div>
                </li>
              </ul>
            </div>
            <!-- End Notification bar -->
          </li>

          <li class="dropdown user-box">
            <a href="#" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">

              <!--<img src="users/avatar-1.jpg" alt="user-img" class="img-circle user-img">-->
              <%= image_tag  "users/avatar-1.jpg", class: "img-circle user-img" , alt: "user-img"  %>

              <div class="user-status away"><i class="zmdi zmdi-dot-circle"></i></div>
            </a>

            <ul class="dropdown-menu">
              <li><a href="javascript:void(0)"><i class="ti-user m-r-5"></i> Profile</a></li>
              <li><a href="javascript:void(0)"><i class="ti-settings m-r-5"></i> Settings</a></li>
              <li><a href="javascript:void(0)"><i class="ti-lock m-r-5"></i> Lock screen</a></li>
              <li><a href="javascript:void(0)"><i class="ti-power-off m-r-5"></i> Logout</a></li>
            </ul>
          </li>
        </ul>

      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>
<!-- Top Bar End -->

app/views/subjects/_form.html.erb
<%= form_for @subject do |form| %>
    <% if @subject.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

          <ul>
            <% @subject.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :subject_name %>
    </div>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :title %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/subjects/create.html.erb
<h1>Subjects#create</h1>
<p>Find me in app/views/subjects/create.html.erb</p>

app/views/subjects/destroy.html.erb
<h1>Subjects#destroy</h1>
<p>Find me in app/views/subjects/destroy.html.erb</p>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subject_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
  <tr>
    <th>name</th>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @subject.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.title %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>title:</strong>
  <%= @subject.title %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subject_path %>

app/views/subjects/update.html.erb
<h1>Subjects#update</h1>
<p>Find me in app/views/subjects/update.html.erb</p>

app/views/teachers/_edit_model.html.erb
<div id="teacher-edit-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div>

        <h1>Editing Teacher</h1>

        <%= render 'form' %>

        <%= link_to 'Show', @teacher %> |
        <%= link_to 'Back', teachers_path %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/_form.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card-box">
      <%= form_for @teacher do |form| %>
          <% if @teacher.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>
                <ul>
                  <% @teacher.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          <div class="form-group">
            <label for="userName">Name:</label>
            <%= form.text_field :name, id: :teacher_name, class:"form-control", placeholder:"Enter name" %>
          </div>
          <div class="form-group">
            <label for="emailAddress">Address*</label>
            <%= form.text_field :address, id: :address, class:"form-control", placeholder:"Enter Address" %>
          </div>
          <div class="form-group">
            <label for="pass1">Phone No*</label>
            <%= form.text_field :phone, id: :phone, class:"form-control", placeholder:"Enter Phone No" %>
          </div>
          <div class="form-group">
            <label for="emailAddress">Email address*</label>
            <%= form.text_field :email, id: :email , type: "email" , class:"form-control", placeholder:"Enter email"%>
          </div>
          <div class="form-group text-right m-b-0">
            <%= form.submit "submit",  class: "btn btn-primary " %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/teachers/_teacher_modal.html.erb
<div id="teacher-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div>
        <p id="notice"><%= notice %></p>
          <div class="card-box">
            <div class="table-responsive">
              <table class="table">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Name:</th>
                  <th>Adress</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>1</td>
                  <td><%= @teacher.name %></td>
                  <td><%= @teacher.address %></td>
                  <td><%= @teacher.phone %></td>
                  <td><%= @teacher.email %></td>
                  <td><span class="label label-danger">Released</span></td>
                  <td>Coderthemes</td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/add_subjects.html.erb
<h2 >hi</h2>
<%= form_tag save_subject_teacher_path  do %>
    <%= select_tag :subject_id, options_for_select( @subjects.all.collect {|d| [ d.name, d.id ] }) %>
    <%= submit_tag "Add" %>
<% end %>

app/views/teachers/create.html.erb
<h1>Teachers#create</h1>
<p>Find me in app/views/teachers/create.html.erb</p>

app/views/teachers/destroy.html.erb
<h1>Teachers#destroy</h1>
<p>Find me in app/views/teachers/destroy.html.erb</p>

app/views/teachers/edit.js.erb
$('#teacher-content').html("<%= j render 'teachers/edit_model', teacher: @teacher %>");
$('#teacher-edit-modal').modal('show');

app/views/teachers/index.html.erb
<%= link_to 'New Teacher', new_teacher_path %>
<p id="notice"><%= notice %></p>
<div class="col-lg-10">
  <div class="card-box">
    <h4 class="header-title m-t-0 m-b-30" align="center">Teachers List</h4>
    <div class="table-responsive">
      <table class="table">
        <thead>
        <tr>
          <th>name</th>
          <th>address</th>
          <th>phone</th>
          <th>email</th>
          <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>

          <% @teacher.each do |teacher| %>
            <tr>
              <td><%= teacher.name %></td>
              <td><%= teacher.address %></td>
              <td><%= teacher.phone %></td>
              <td><%= teacher.email %></td>
              <td><%= link_to 'Show', teacher_path(teacher), remote: true %></td>
              <td><%= link_to 'Edit', edit_teacher_path(teacher), remote: true  %></td>
              <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id='teacher-content'></div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/save_subject.html.erb
<p><%= flash[:success] %></p>

app/views/teachers/show.js.erb
$('#teacher-content').html("<%= j render 'teacher_modal', teacher: @teacher %>");
$('#teacher-modal').modal('show');

app/views/teachers/subjects.html.erb
<p id="notice"><%= notice %></p>

<h1>Subject Of this Teacher</h1>

<table>
  <thead>
  <tr>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @teacher.subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "add subject",  add_subjects_teacher_path %>

app/views/teachers/update.html.erb
<h1>Teachers#update</h1>
<p>Find me in app/views/teachers/update.html.erb</p>